In [1]:
import pandas as pd
import os

In [2]:
sentences_file = "data/frases-musicas-final-filled.csv"
annotations_dir = "data/annotations/20251203"
assignments_file = "data/assignments_second_round.csv"

In [3]:
sentences_df = pd.read_csv(sentences_file)
assignments_df = pd.read_csv(assignments_file)

In [4]:
sentences_df.head()

,music_id,music_frase_id,frase,frase_id,tem_padrao,padrao_encontrado
0,1,1,Carolina é uma menina bem difícil de esquecer.,1,Female,"[(1916877163388338700, 3, 6), (191687716338833..."
1,1,2,Andar bonito e um brilho no olhar.,2,N,NaN
2,1,3,Tem um jeito adolescente que me faz enlouquecer.,3,N,NaN
3,1,4,E um molejo que eu não vou te enganar.,4,N,NaN
4,1,5,"Maravilha feminina, meu docinho de pavê.",5,N,NaN

In [5]:
assignments_df.head()

   frase_id annotator_id
0    594474       user01
1    594474       user02
2     32675       user02
3     32675       user03
4   3362704       user03

In [6]:
# lista todos os arquivos do diretorio de anotações
annotation_files = [
    os.path.join(annotations_dir, f)
    for f in os.listdir(annotations_dir)
    if f.endswith(".csv") and f.startswith("annotation_second_round_user")
]
annotation_files

['data/annotations/20251203/annotation_second_round_user09.csv',
 'data/annotations/20251203/annotation_second_round_user21.csv',
 'data/annotations/20251203/annotation_second_round_user20.csv',
 'data/annotations/20251203/annotation_second_round_user08.csv',
 'data/annotations/20251203/annotation_second_round_user18.csv',
 'data/annotations/20251203/annotation_second_round_user19.csv',
 'data/annotations/20251203/annotation_second_round_user03.csv',
 'data/annotations/20251203/annotation_second_round_user17.csv',
 'data/annotations/20251203/annotation_second_round_user16.csv',
 'data/annotations/20251203/annotation_second_round_user02.csv',
 'data/annotations/20251203/annotation_second_round_user14.csv',
 'data/annotations/20251203/annotation_second_round_user01.csv',
 'data/annotations/20251203/annotation_second_round_user15.csv',
 'data/annotations/20251203/annotation_second_round_user11.csv',
 'data/annotations/20251203/annotation_second_round_user05.csv',
 'data/annotations/20251203/annotation_second_round_user04.csv',
 'data/annotations/20251203/annotation_second_round_user10.csv',
 'data/annotations/20251203/annotation_second_round_user06.csv',
 'data/annotations/20251203/annotation_second_round_user12.csv',
 'data/annotations/20251203/annotation_second_round_user13.csv',
 'data/annotations/20251203/annotation_second_round_user07.csv']

In [7]:
annotations_df = None
if len(annotation_files) > 0:
    annotations_df = pd.read_csv(annotation_files[0])
    for f in annotation_files[1:]:
        df = pd.read_csv(f)
        annotations_df = pd.concat([annotations_df, df], ignore_index=True)
annotations_df

,user,frase_id,annotation,sentiment
0,user09,3873264,"[""aparencia""]",positiva
1,user09,1311085,"[""identidade"", ""aparencia"", ""comportamentos""]",positiva
2,user09,3106781,"[""aparencia""]",positiva
3,user09,2485504,"[""identidade"", ""comportamentos""]",positiva
4,user09,3507498,"[""aparencia""]",positiva
...,...,...,...,...
24682,user07,782416,"[""identidade"", ""aparencia""]",positiva
24683,user07,1131661,"[""identidade"", ""habilidades"", ""valores""]",positiva
24684,user07,2193362,"[""identidade"", ""aparencia"", ""papel_social"", ""h...",positiva
24685,user07,1305677,"[""comportamentos""]",positiva
24686,user07,3622792,"[""identidade"", ""valores""]",negativa

In [8]:
assignments_with_annotations = assignments_df.merge(
    annotations_df,
    left_on=["annotator_id", "frase_id"],
    right_on=["user", "frase_id"],
    how="left",
    
)
assignments_with_annotations

,frase_id,annotator_id,user,annotation,sentiment
0,594474,user01,user01,"[""valores""]",positiva
1,594474,user02,user02,"[""papel_social"", ""valores""]",positiva
2,32675,user02,user02,"[""identidade"", ""aparencia"", ""papel_social"", ""h...",negativa
3,32675,user03,user03,"[""comportamentos""]",negativa
4,3362704,user03,user03,"[""habilidades""]",positiva
...,...,...,...,...,...
32327,98857,user17,user17,"[""aparencia""]",positiva
32328,487639,user16,NaN,NaN,NaN
32329,487639,user18,NaN,NaN,NaN
32330,3478220,user17,user17,"[""identidade"", ""comportamentos""]",positiva
32331,3478220,user19,user19,"[""identidade"", ""papel_social"", ""comportamentos""]",positiva

In [9]:
# em assignments_with_annotations, caso user seja NaN, preencher com o valor de annotator_id
assignments_with_annotations["user"] = assignments_with_annotations["user"].fillna(assignments_with_annotations["annotator_id"])
assignments_with_annotations["annotation"] = assignments_with_annotations["annotation"].fillna("not_annotated") 
assignments_with_annotations

,frase_id,annotator_id,user,annotation,sentiment
0,594474,user01,user01,"[""valores""]",positiva
1,594474,user02,user02,"[""papel_social"", ""valores""]",positiva
2,32675,user02,user02,"[""identidade"", ""aparencia"", ""papel_social"", ""h...",negativa
3,32675,user03,user03,"[""comportamentos""]",negativa
4,3362704,user03,user03,"[""habilidades""]",positiva
...,...,...,...,...,...
32327,98857,user17,user17,"[""aparencia""]",positiva
32328,487639,user16,user16,not_annotated,NaN
32329,487639,user18,user18,not_annotated,NaN
32330,3478220,user17,user17,"[""identidade"", ""comportamentos""]",positiva
32331,3478220,user19,user19,"[""identidade"", ""papel_social"", ""comportamentos""]",positiva

In [10]:
assignments_with_annotations = assignments_with_annotations.merge(
    sentences_df[["frase_id", "frase", "tem_padrao"]],
    on="frase_id",
    how="left"
)
assignments_with_annotations

,frase_id,annotator_id,user,annotation,sentiment,frase,tem_padrao
0,594474,user01,user01,"[""valores""]",positiva,Que o rei será bendito.,Male
1,594474,user02,user02,"[""papel_social"", ""valores""]",positiva,Que o rei será bendito.,Male
2,32675,user02,user02,"[""identidade"", ""aparencia"", ""papel_social"", ""h...",negativa,"Mina doidona taca fogo, passa a goma, compra t...",Female
3,32675,user03,user03,"[""comportamentos""]",negativa,"Mina doidona taca fogo, passa a goma, compra t...",Female
4,3362704,user03,user03,"[""habilidades""]",positiva,Ela dança gostosinho.,Female
...,...,...,...,...,...,...,...
32327,98857,user17,user17,"[""aparencia""]",positiva,As mulheres lindas que tem no.,Female
32328,487639,user16,user16,not_annotated,NaN,Ele é fiel e nunca deixa um filho seu sozinho ...,Male
32329,487639,user18,user18,not_annotated,NaN,Ele é fiel e nunca deixa um filho seu sozinho ...,Male
32330,3478220,user17,user17,"[""identidade"", ""comportamentos""]",positiva,Ela é a paz pro.,Female
32331,3478220,user19,user19,"[""identidade"", ""papel_social"", ""comportamentos""]",positiva,Ela é a paz pro.,Female

In [11]:
assignments_with_annotations['annotation'].value_counts()

annotation
not_annotated                                                     7645
["identidade"]                                                    4715
["comportamentos"]                                                3086
["aparencia"]                                                     2586
["outros"]                                                        2157
                                                                  ...
["papel_social", "comportamentos", "outros"]                         1
["identidade", "papel_social", "valores", "outros"]                  1
["aparencia", "papel_social", "habilidades", "comportamentos"]       1
["papel_social", "valores", "outros"]                                1
["papel_social", "habilidades", "valores", "comportamentos"]         1
Name: count, Length: 88, dtype: int64

In [25]:
# import ast

# awa = assignments_with_annotations.copy()
# awa['annotation_list'] = awa['annotation'].apply(lambda x: ast.literal_eval(x) if x != 'not_annotated' else [])

# annotation_statistics_df = awa.groupby('frase_id')['annotation_list'].apply(list).reset_index()
# annotation_statistics_df['total_annotations'] = annotation_statistics_df['annotation_list'].apply(lambda x: sum(len(ann) for ann in x))
# def count_annotation(ann_list, ann_type):
#     return sum(ann.count(ann_type) for ann in ann_list)

# for ann_type in ['identidade', 'aparencia', 'papel_social', 'habilidades', 'valores', 'comportamentos', 'outros']:
#     annotation_statistics_df[ann_type] = annotation_statistics_df['annotation_list'].apply(lambda x: count_annotation(x, ann_type))
# annotation_statistics_df['valid_annotations'] = annotation_statistics_df['total_annotations']
# annotation_statistics_df = annotation_statistics_df.drop(columns=['annotation_list'])
# annotation_statistics_df


import ast
from collections import Counter

awa = assignments_with_annotations.copy()

# Convert annotation strings to lists, turning 'not_annotated' into empty lists
awa['annotation_list'] = awa['annotation'].apply(
    lambda x: ast.literal_eval(x) if x != 'not_annotated' else []
)

# Group by frase_id and gather all annotation lists per frase
annotation_statistics_df = (
    awa.groupby('frase_id')['annotation_list']
       .apply(list)
       .reset_index()
)

# Total annotations = total number of items across all lists
annotation_statistics_df['total_annotations'] = annotation_statistics_df['annotation_list'].apply(
    lambda lists: sum(len(lst) for lst in lists)
)

# Count specific annotations
def count_annotation(list_of_lists, ann_type):
    return sum(lst.count(ann_type) for lst in list_of_lists)

annotation_types = [
    'identidade', 'aparencia', 'papel_social', 'habilidades',
    'valores', 'comportamentos', 'outros'
]

for ann_type in annotation_types:
    annotation_statistics_df[ann_type] = annotation_statistics_df['annotation_list'].apply(
        lambda lists: count_annotation(lists, ann_type)
    )

# valid annotations = same as total_annotations (since 'not_annotated' → [])
annotation_statistics_df['valid_annotations'] = annotation_statistics_df['total_annotations']

# Majority vote calculation
def get_majority_vote(list_of_lists):
    flat = [item for sublist in list_of_lists for item in sublist]
    if not flat:
        return None
    counts = Counter(flat)
    return counts.most_common(1)[0][0]

annotation_statistics_df['majority_vote'] = annotation_statistics_df['annotation_list'].apply(
    get_majority_vote
)

# Agreement rate = % of annotators who assigned the majority vote
def agreement_rate(list_of_lists, majority_vote):
    if majority_vote is None:
        return 0.0
    total_annotators = len(list_of_lists)
    if total_annotators == 0:
        return 0.0
    agreeing = sum(1 for lst in list_of_lists if majority_vote in lst)
    return agreeing * 100 / total_annotators

annotation_statistics_df['agreement_rate'] = annotation_statistics_df.apply(
    lambda row: agreement_rate(row['annotation_list'], row['majority_vote']),
    axis=1
)

# Remove raw annotation list
annotation_statistics_df = annotation_statistics_df.drop(columns=['annotation_list'])

annotation_statistics_df

,frase_id,total_annotations,identidade,aparencia,papel_social,habilidades,valores,comportamentos,outros,valid_annotations,majority_vote,agreement_rate
0,1,2,2,0,0,0,0,0,0,2,identidade,100.0
1,6,5,1,2,0,2,0,0,0,5,aparencia,100.0
2,51,3,1,2,0,0,0,0,0,3,aparencia,100.0
3,798,1,1,0,0,0,0,0,0,1,identidade,50.0
4,1235,1,0,1,0,0,0,0,0,1,aparencia,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...
16161,4572368,2,2,0,0,0,0,0,0,2,identidade,100.0
16162,4572851,2,0,0,0,1,0,0,1,2,outros,50.0
16163,4572890,3,1,0,0,0,1,0,1,3,identidade,50.0
16164,4573057,2,0,0,0,0,1,1,0,2,valores,50.0
16165,4573086,1,1,0,0,0,0,0,0,1,identidade,50.0

In [26]:
annotation_statistics_df[annotation_statistics_df['valid_annotations'] > 0]

,frase_id,total_annotations,identidade,aparencia,papel_social,habilidades,valores,comportamentos,outros,valid_annotations,majority_vote,agreement_rate
0,1,2,2,0,0,0,0,0,0,2,identidade,100.0
1,6,5,1,2,0,2,0,0,0,5,aparencia,100.0
2,51,3,1,2,0,0,0,0,0,3,aparencia,100.0
3,798,1,1,0,0,0,0,0,0,1,identidade,50.0
4,1235,1,0,1,0,0,0,0,0,1,aparencia,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...
16161,4572368,2,2,0,0,0,0,0,0,2,identidade,100.0
16162,4572851,2,0,0,0,1,0,0,1,2,outros,50.0
16163,4572890,3,1,0,0,0,1,0,1,3,identidade,50.0
16164,4573057,2,0,0,0,0,1,1,0,2,valores,50.0
16165,4573086,1,1,0,0,0,0,0,0,1,identidade,50.0

In [27]:
annotation_statistics_df[annotation_statistics_df['valid_annotations'] >= 2]

,frase_id,total_annotations,identidade,aparencia,papel_social,habilidades,valores,comportamentos,outros,valid_annotations,majority_vote,agreement_rate
0,1,2,2,0,0,0,0,0,0,2,identidade,100.0
1,6,5,1,2,0,2,0,0,0,5,aparencia,100.0
2,51,3,1,2,0,0,0,0,0,3,aparencia,100.0
5,1277,4,2,1,0,0,1,0,0,4,identidade,100.0
6,1280,4,2,0,0,1,1,0,0,4,identidade,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
16160,4571726,4,1,0,0,0,1,1,1,4,outros,50.0
16161,4572368,2,2,0,0,0,0,0,0,2,identidade,100.0
16162,4572851,2,0,0,0,1,0,0,1,2,outros,50.0
16163,4572890,3,1,0,0,0,1,0,1,3,identidade,50.0
16164,4573057,2,0,0,0,0,1,1,0,2,valores,50.0

In [28]:
annotation_statistics_df['valid_annotations'].describe()

count    16166.000000
mean         2.380428
std          1.343193
min          0.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         10.000000
Name: valid_annotations, dtype: float64

In [29]:
annotation_statistics_df['valid_annotations'].value_counts()

valid_annotations
2     5326
3     3746
1     3322
4     1819
0      854
5      737
6      258
7       79
8       19
9        4
10       2
Name: count, dtype: int64

In [30]:
annotation_statistics_df_full = pd.merge(
    annotation_statistics_df.reset_index(),
    sentences_df[["frase_id", "frase", "tem_padrao"]],
    on="frase_id",
    how="left"
)
annotation_statistics_df_full

,index,frase_id,total_annotations,identidade,aparencia,papel_social,habilidades,valores,comportamentos,outros,valid_annotations,majority_vote,agreement_rate,frase,tem_padrao
0,0,1,2,2,0,0,0,0,0,0,2,identidade,100.0,Carolina é uma menina bem difícil de esquecer.,Female
1,1,6,5,1,2,0,2,0,0,0,5,aparencia,100.0,"Inteligente, ela é muito sensual.",Female
2,2,51,3,1,2,0,0,0,0,0,3,aparencia,100.0,"Menina bela, menina bela.",Female
3,3,798,1,1,0,0,0,0,0,0,1,identidade,50.0,Ele não é feliz.,Male
4,4,1235,1,0,1,0,0,0,0,0,1,aparencia,50.0,"Ela é linda, mas não tem nome.",Female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16161,16161,4572368,2,2,0,0,0,0,0,0,2,identidade,100.0,Abaixo do céu todo homem é igual.,Male
16162,16162,4572851,2,0,0,0,1,0,0,1,2,outros,50.0,Embora a inteligência do homem seja grande par...,Male
16163,16163,4572890,3,1,0,0,0,1,0,1,3,identidade,50.0,Para ser compassivo antes precisa da consciênc...,Female
16164,16164,4573057,2,0,0,0,0,1,1,0,2,valores,50.0,O homem mentalmente espiritualizado é falante.,Male
16165,16165,4573086,1,1,0,0,0,0,0,0,1,identidade,50.0,"O homem atual, na grande maioria, é carente da...",Male

In [31]:
annotation_statistics_df_full['tem_padrao'].value_counts()

tem_padrao
Female    9917
Male      6163
N           86
Name: count, dtype: int64

In [32]:
annotation_statistics_df_full["real_class"] = annotation_statistics_df_full["tem_padrao"].map({
    "Female": "sim",
    "Male": "sim",
    "N": "nao"
})
annotation_statistics_df_full

,index,frase_id,total_annotations,identidade,aparencia,papel_social,habilidades,valores,comportamentos,outros,valid_annotations,majority_vote,agreement_rate,frase,tem_padrao,real_class
0,0,1,2,2,0,0,0,0,0,0,2,identidade,100.0,Carolina é uma menina bem difícil de esquecer.,Female,sim
1,1,6,5,1,2,0,2,0,0,0,5,aparencia,100.0,"Inteligente, ela é muito sensual.",Female,sim
2,2,51,3,1,2,0,0,0,0,0,3,aparencia,100.0,"Menina bela, menina bela.",Female,sim
3,3,798,1,1,0,0,0,0,0,0,1,identidade,50.0,Ele não é feliz.,Male,sim
4,4,1235,1,0,1,0,0,0,0,0,1,aparencia,50.0,"Ela é linda, mas não tem nome.",Female,sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16161,16161,4572368,2,2,0,0,0,0,0,0,2,identidade,100.0,Abaixo do céu todo homem é igual.,Male,sim
16162,16162,4572851,2,0,0,0,1,0,0,1,2,outros,50.0,Embora a inteligência do homem seja grande par...,Male,sim
16163,16163,4572890,3,1,0,0,0,1,0,1,3,identidade,50.0,Para ser compassivo antes precisa da consciênc...,Female,sim
16164,16164,4573057,2,0,0,0,0,1,1,0,2,valores,50.0,O homem mentalmente espiritualizado é falante.,Male,sim
16165,16165,4573086,1,1,0,0,0,0,0,0,1,identidade,50.0,"O homem atual, na grande maioria, é carente da...",Male,sim

In [50]:
annotation_statistics_df_full[annotation_statistics_df_full['valid_annotations']>=2]

,index,frase_id,total_annotations,identidade,aparencia,papel_social,habilidades,valores,comportamentos,outros,valid_annotations,majority_vote,agreement_rate,frase,tem_padrao,real_class
0,0,1,2,2,0,0,0,0,0,0,2,identidade,100.0,Carolina é uma menina bem difícil de esquecer.,Female,sim
1,1,6,5,1,2,0,2,0,0,0,5,aparencia,100.0,"Inteligente, ela é muito sensual.",Female,sim
2,2,51,3,1,2,0,0,0,0,0,3,aparencia,100.0,"Menina bela, menina bela.",Female,sim
5,5,1277,4,2,1,0,0,1,0,0,4,identidade,100.0,"Ela é guerreira, ela é uma deusa, ela é mulher...",Female,sim
6,6,1280,4,2,0,0,1,1,0,0,4,identidade,100.0,Ela é discreta e cultua bons livros.,Female,sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16160,16160,4571726,4,1,0,0,0,1,1,1,4,outros,50.0,Por isto o homem mente racional.,Male,sim
16161,16161,4572368,2,2,0,0,0,0,0,0,2,identidade,100.0,Abaixo do céu todo homem é igual.,Male,sim
16162,16162,4572851,2,0,0,0,1,0,0,1,2,outros,50.0,Embora a inteligência do homem seja grande par...,Male,sim
16163,16163,4572890,3,1,0,0,0,1,0,1,3,identidade,50.0,Para ser compassivo antes precisa da consciênc...,Female,sim
16164,16164,4573057,2,0,0,0,0,1,1,0,2,valores,50.0,O homem mentalmente espiritualizado é falante.,Male,sim

In [35]:
annotation_statistics_df_full['agreement_rate'].describe()

count    16166.000000
mean        66.485216
std         28.577676
min          0.000000
25%         50.000000
50%         50.000000
75%        100.000000
max        100.000000
Name: agreement_rate, dtype: float64

In [36]:
import plotly.express as px

annotated_sentences = annotation_statistics_df_full[annotation_statistics_df_full['valid_annotations'] > 0]
total_sentences = annotation_statistics_df_full['frase_id'].nunique()
summary_counts = pd.DataFrame({
    'total_frases': [total_sentences],
    'frases_anotadas': [len(annotated_sentences)],
    'taxa_cobertura_pct': [
        (len(annotated_sentences) / total_sentences * 100) if total_sentences else float('nan')
    ]
})
summary_counts.round(2)

   total_frases  frases_anotadas  taxa_cobertura_pct
0         16166            15312               94.72

In [37]:
category_counts = (
    annotated_sentences['majority_vote']
    .dropna()
    .value_counts()
    .rename_axis('categoria')
    .reset_index(name='frases')
    .sort_values('frases', ascending=False)
)
category_counts

        categoria  frases
0      identidade    7440
1  comportamentos    2366
2       aparencia    2322
3          outros    1404
4         valores     676
5    papel_social     608
6     habilidades     496

In [48]:
# if not category_counts.empty:
#     fig = px.bar(
#         category_counts,
#         x='categoria',
#         y='frases',
#         text='frases',
#         title='Distribuição de frases anotadas por categoria',
#     )
#     fig.update_traces(texttemplate='%{text}', textposition='outside')
#     fig.update_layout(
#         yaxis_title='Número de frases',
#         xaxis_title='Categoria',
#         uniformtext_minsize=12,
#         uniformtext_mode='hide'
#     )
#     fig.show()
# else:
#     print('Sem categorias anotadas para exibir.')

LABELS = {
    "identidade": "Identidade",
    "aparencia": "Aparência",
    "papel_social": "Papel social",
    "habilidades": "Habilidades/Competências",
    "valores": "Valores/Crenças",
    "comportamentos": "Comportamentos",
    "outros": "Outros",
}

if not category_counts.empty:

    # Ordena pelas categorias mais frequentes
    category_counts = category_counts.sort_values('frases', ascending=False).copy()

    # Mapeia nomes amigáveis
    category_counts['label_categoria'] = category_counts['categoria'].map(LABELS)

    fig = px.bar(
        category_counts,
        x='categoria',
        y='frases',
        text='frases',   # <-- agora o texto é só o número
        title='Distribuição de frases anotadas por categoria',
        color='categoria',
        color_discrete_sequence=px.colors.qualitative.Set2
    )

    fig.update_traces(
        texttemplate='%{text}',
        textposition='outside',
        hovertemplate='<b>%{label_categoria}</b><br>Frases: %{y}<extra></extra>'
    )

    fig.update_layout(
        template='simple_white',
        showlegend=False,  # <-- remove legenda
        yaxis_title='Número de frases',
        xaxis_title='Categoria',
        uniformtext_minsize=12,
        uniformtext_mode='hide',
        title_x=0.5,
        margin=dict(l=40, r=20, t=60, b=80),
        height=500,
        xaxis=dict(
            tickangle=-30,
            tickmode='array',
            tickvals=category_counts['categoria'],
            ticktext=category_counts['label_categoria'],  # nomes amigáveis no eixo X
            categoryorder='total descending'
        )
    )

    # Mais espaço para o número no topo
    max_y = category_counts['frases'].max()
    fig.update_yaxes(range=[0, max_y * 1.25])

    fig.show()

else:
    print('Sem categorias anotadas para exibir.')

In [39]:
agreement_series = annotated_sentences['agreement_rate'].dropna()
agreement_summary = pd.DataFrame({
    'agreement_medio_pct': [agreement_series.mean()],
    'agreement_desvio_pct': [agreement_series.std()],
    'frases_consideradas': [len(agreement_series)]
})
agreement_summary.round(2)

   agreement_medio_pct  agreement_desvio_pct  frases_consideradas
0                70.19                 24.53                15312

In [40]:
agreement_by_class = (
    annotated_sentences[annotated_sentences['majority_vote'].notna()]
    .groupby('majority_vote')['agreement_rate']
    .agg(['count', 'mean', 'std'])
    .reset_index()
    .rename(columns={
        'majority_vote': 'categoria',
        'count': 'frases',
        'mean': 'agreement_medio_pct',
        'std': 'agreement_desvio_pct'
    })
    .sort_values('agreement_medio_pct', ascending=False)
)
agreement_by_class.round({
    'agreement_medio_pct': 2,
    'agreement_desvio_pct': 2
})

        categoria  frases  agreement_medio_pct  agreement_desvio_pct
0       aparencia    2322                77.22                 24.91
1  comportamentos    2366                74.49                 25.00
3      identidade    7440                70.03                 24.50
6         valores     676                66.49                 23.53
5    papel_social     608                64.47                 22.69
2     habilidades     496                63.91                 22.43
4          outros    1404                58.65                 18.92

In [49]:
# if not agreement_by_class.empty:
#     fig = px.bar(
#         agreement_by_class,
#         x='categoria',
#         y='agreement_medio_pct',
#         error_y='agreement_desvio_pct',
#         text='agreement_medio_pct',
#         title='Agreement médio por categoria (com desvio padrão)',
#     )
#     fig.update_traces(texttemplate='%{text:.2f}%', textposition='outside')
#     y_max = agreement_by_class['agreement_medio_pct'].max()
#     y_err = agreement_by_class['agreement_desvio_pct'].fillna(0).max()
#     fig.update_layout(
#         yaxis_title='Agreement médio (%)',
#         xaxis_title='Categoria',
#         yaxis_range=[0, min(100, y_max + y_err * 1.1)],
#         uniformtext_minsize=10,
#         uniformtext_mode='hide'
#     )
#     fig.show()
# else:
#     print('Sem dados de agreement por categoria para exibir.')

LABELS = {
    "identidade": "Identidade",
    "aparencia": "Aparência",
    "papel_social": "Papel social",
    "habilidades": "Habilidades/Competências",
    "valores": "Valores/Crenças",
    "comportamentos": "Comportamentos",
    "outros": "Outros",
}

if not agreement_by_class.empty:
    # Ordena pelas categorias com maior agreement médio
    agreement_by_class = agreement_by_class.sort_values(
        'agreement_medio_pct', ascending=False
    ).copy()

    # Nome amigável da categoria
    agreement_by_class['label_categoria'] = agreement_by_class['categoria'].map(LABELS)

    fig = px.bar(
        agreement_by_class,
        x='categoria',
        y='agreement_medio_pct',
        error_y='agreement_desvio_pct',
        text='agreement_medio_pct',  # texto = valor numérico
        title='Agreement médio por categoria (com desvio padrão)',
        color='categoria',
        color_discrete_sequence=px.colors.qualitative.Set2,
    )

    fig.update_traces(
        texttemplate='%{text:.1f}%',  # uma casa decimal + %
        textposition='outside',
        hovertemplate=(
            '<b>%{customdata[0]}</b><br>'
            'Agreement médio: %{y:.1f}%<br>'
            'Desvio padrão: %{customdata[1]:.1f}%'
            '<extra></extra>'
        ),
        customdata=agreement_by_class[['label_categoria', 'agreement_desvio_pct']].values
    )

    y_max = agreement_by_class['agreement_medio_pct'].max()
    y_err = agreement_by_class['agreement_desvio_pct'].fillna(0).max()

    fig.update_layout(
        template='simple_white',
        showlegend=False,  # sem legenda
        yaxis_title='Agreement médio (%)',
        xaxis_title='Categoria',
        title_x=0.5,
        uniformtext_minsize=10,
        uniformtext_mode='hide',
        margin=dict(l=40, r=20, t=60, b=80),
        height=500,
        xaxis=dict(
            tickangle=-30,
            tickmode='array',
            tickvals=agreement_by_class['categoria'],
            ticktext=agreement_by_class['label_categoria'],
            categoryorder='array',
            categoryarray=agreement_by_class['categoria'].tolist()
        ),
        yaxis=dict(
            range=[0, min(100, y_max + y_err * 1.25)]
        )
    )

    fig.show()
else:
    print('Sem dados de agreement por categoria para exibir.')

In [41]:
annotation_statistics_df_full.to_csv("data/second_stage_annotations.csv", index=False)

In [43]:
annotation_statistics_df_full[['frase_id','frase','majority_vote']].to_csv("data/filtered_second_stage_annotations.csv", index=False)